#!/usr/bin/env bash

sudo tail -f -q -n 0 /var/lib/docker/volumes/sa-demo-423_rasp-logs/_data/acme-java/event.log /var/lib/docker/volumes/sa-demo-423_rasp-logs/_data/acme-dotnetcore/event.log /var/lib/docker/volumes/sa-demo-423_rasp-logs/_data/struts2showcase/event.log | jq -r '"===> App: \(.app) | Severity: \(.severity) | Timestamp: \(.timestamp) | Category: \(.category) | Action: \(.action) | SrcIP: \(.src_host) | URL: \(.url) | CMD: \(.report.command_line) | Query: \(.report.query) | Data: \(.report.input)\n"'
